{% set name = "django-fsm-log" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-fsm-log-{{ version }}.tar.gz
  sha256: 9ef766f5e6d7c573d1953cf91df73538a611373cc1ef97488eff19a3f71d6ed6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.11
    - django >=1.8
    - django-fsm >=2
    - django-appconf

test:
  imports:
    - django_fsm_log
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gizmag/django-fsm-log
  summary: Logging for django-fsm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
